name: Deploy TODO List
on:
    push:
        branches:
         - "main"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
        - name: NPM Install 
          run: npm ci
          working-directory: .
        - name: Build app
          run: npm run build
          working-directory: .
        - name: Deploy
          uses: JamesIves/github-pages-deploy@4.1.5
          with:
            branch: todo-list-react
            folder: build